---
services:
  bot:
    image: ghcr.io/federation-interservices-d-informatique/fiibot-logger:2.1.4
    env_file: .env
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine
    env_file: .env
    restart: always
    ports:
      - 127.0.0.1:6905:5432
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - fiibot-logger-postgres:/var/lib/postgresql/data

volumes:
  fiibot-logger-postgres:
    driver: local
